### ISSUE TITLE
Undebates Landing Page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#109]
```
<UndebatesLandingPage 
    className={}
    style={}
    {...props}
>
```
This is the first thing new election administrators will see when considering undebates for their elections.  As we build this component, we will take as much of the text and content out of props as we can. This makes it easier to change on the fly - without having to update the server.   The props will be set in Iotas.json.    There are names for the props provided, but they are guidlines and more descriptive or more standardized names are welcome. 

- [x] The top bar should be the UndebatesHeaderBar component. There is a slight difference in look - just ignore the difference.
- [x] props.line1 and props.line2 will be the text for the "Automated Video Q&A", "for every candidate, for every election, across the country"
- [x] The main image will be rendered from #120. The props to pass to it should come from props.topIframe
- [x] the Statement component will render What are Undebates and it's text.  <Statement {...props.statement[0]} /> Statement will take subject and description. #112   This component should set the width that it wants the Statement component to fill
- [x] the "Create Your Own Undebate" button will be an instance of the SingInSignUp component.  props.secondarySignupButton could be where the text for this actually comes from.
- [x] The three boxes with images and text will be <IconBox {...props.IconBox[0]}>  where IconBox takes IconName, subject, description as props. #113
- [x] How It Works will be props.statement[1]
- [x] LandingTimeline #111 will be a separate component. 
- [x] Frequently Asked Questions #114 will be the <FAQ {...props.faq}> where faq is [{q: "", a: ""},{q: "", a: ""}, ...]
- [x] The bottom will be <UndebateFooter /> #110
- [x] Component layout will need to adapt for the [smartphone layout](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2268%3A5302)
- [x] First create a story for this, but put the props in iotas.json and import iotas.json into the story, and then filter it for path==='undebates'
- [x] after the story is working, in app/web-components/ create undebates-landing-page.js see app/web-components/home for a starting point. 
- [x] make sure you have your MONGODB_URI setup and then do `npm run dev` and browse to localhost:3011/undebates

[![image](https://user-images.githubusercontent.com/3317487/154740626-a6187ab3-b16e-418d-b56c-5e457ee3fd48.png)](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2000%3A4177)

**Comment by ddfridley** [comment]
@Gluay88 can you try adding the font-faces from [app/assets/styles/index.css](https://github.com/EnCiv/undebate-ssp/blob/main/assets/styles/index.css) to the UndebatesLandingPage  component, using [react-jss#font-face](https://cssinjs.org/jss-syntax/?v=v10.9.0#font-face). That css file doesn't get included when you npm run dev, and we need to  avoid having global css files .  undebate-ssp uses these fonts, but other pages use other fonts and would need a different css file - if we were doing that.  IT would be convenient if it could work this way.

**Comment by Gluay88** [comment]
Will do. Thank you.

**Comment by ddfridley** [comment]
closed by #159
