### ISSUE TITLE
Undebates Home page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#20]
After someone signs in they will go to this page.
How an account gets creates is out of scope for this. (we do it by manually putting it in the database)

See <UndebatesHeaderBar> #22 for the header component

After someone creates Undebates, then the page shows a list of them like  - see <UndebatesLists> #21

Here is a breakdown of the header component: 
https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate?node-id=326%3A2267

Here is the clickable prototype
https://www.figma.com/proto/yXrcMvg5EIwdLkHHxIdILh/Undebate?node-id=326%3A5476&scaling=min-zoom&page-id=326%3A2267&starting-point-node-id=326%3A2331

![image](https://user-images.githubusercontent.com/3317487/131606852-39b1cc07-991b-42b3-a86f-1a2e09ddeec8.png)

- [x]  use the get-election-docs api #71 to get the electionObjs 

- [x] Render UndebatesList #21 passing electionObjs to it

- [x] And if UndebatesList calls onDone with {valid: true, value: id} then it will render the ConfigurationElection component, #23 

- [x] it will use the the subscribe-election-info api #74  to subscribe to the election data for that id

- [x] it will use getElectionStatusMethods #105 and the upsert api #72 to create the electionOM=[electionObj, electionMethods] property to pass to the ConfigurationElection page

- [x] if ConfigurationElection calls onDone, refresh electionObjs and rerender UndebateList

- [x] Create a web-component undebates-homepage that renders this component, and a corresponding entry in iotas.json and get this running on dev.  If the user is not logged in, just show the header and blank below. Later the landing page will be available to go there.

**Comment by ddfridley** [comment]
@kamui-fin I added some task to the bottom of this issue to clarify that it's calling the apis to get data from the server.  Happy to discuss in more detail.

**Comment by ddfridley** [comment]
closed in #157
