### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#56]
```
<Submissions
   className={}
   style={}
   electionOM={[electionObj, electionMethods]}
>

```
See #46 for electionOM details
- [ ] Renders the table of candidates, status, etc
- [ ] See the [discussion in figma](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh?node-id=392:5821#130352071) about possibly combining the two status columns into one
- [ ] The columns can be filtered see the lower figma drawing
- [ ] use the same table component and scrolling component as in #53 
- [ ] The status column is updated elsewhere and each entry is one of ['submitted', 'accepted', 'sent', 'declined'] if there is ever some other word, show the word but no icon. 
- [ ] See the election category component #5 for icons.  Also, is there a way to factor out some common code (not required, may not make sense).

This is highly related to and should share common code with 
- #53 

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=390%3A5166

- [ ] See also the screen below that shows how to filter the columns

![image](https://user-images.githubusercontent.com/3317487/144679930-6a6fab08-0361-4961-b19b-198b4497a8e8.png)

**Comment by BolunThompson** [comment]
I'll take this issue

**Comment by ddfridley** [comment]
Great @BolunThompson!  It may or may not be helpful to look at the candidate table input page. https://github.com/EnCiv/undebate-ssp/blob/main/app/components/candidate-table.js and please see the story for that for how we are pulling the electionOM in from context, and how we are setting defaultElectionObj to pass in default data.
